package com.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.u17lite.Manhua;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MANHUA".
*/
public class ManhuaDao extends AbstractDao<Manhua, String> {

    public static final String TABLENAME = "MANHUA";

    /**
     * Properties of entity Manhua.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Name = new Property(0, String.class, "name", true, "NAME");
        public final static Property Cover = new Property(1, String.class, "cover", false, "COVER");
        public final static Property Tag = new Property(2, String.class, "tag", false, "TAG");
        public final static Property Detial = new Property(3, String.class, "detial", false, "DETIAL");
        public final static Property Comicid = new Property(4, String.class, "comicid", false, "COMICID");
        public final static Property Chapterid = new Property(5, String.class, "chapterid", false, "CHAPTERID");
        public final static Property Collect = new Property(6, boolean.class, "collect", false, "COLLECT");
        public final static Property History = new Property(7, boolean.class, "history", false, "HISTORY");
    }


    public ManhuaDao(DaoConfig config) {
        super(config);
    }
    
    public ManhuaDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MANHUA\" (" + //
                "\"NAME\" TEXT PRIMARY KEY NOT NULL ," + // 0: name
                "\"COVER\" TEXT," + // 1: cover
                "\"TAG\" TEXT," + // 2: tag
                "\"DETIAL\" TEXT," + // 3: detial
                "\"COMICID\" TEXT," + // 4: comicid
                "\"CHAPTERID\" TEXT," + // 5: chapterid
                "\"COLLECT\" INTEGER NOT NULL ," + // 6: collect
                "\"HISTORY\" INTEGER NOT NULL );"); // 7: history
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MANHUA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Manhua entity) {
        stmt.clearBindings();
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(1, name);
        }
 
        String cover = entity.getCover();
        if (cover != null) {
            stmt.bindString(2, cover);
        }
 
        String tag = entity.getTag();
        if (tag != null) {
            stmt.bindString(3, tag);
        }
 
        String detial = entity.getDetial();
        if (detial != null) {
            stmt.bindString(4, detial);
        }
 
        String comicid = entity.getComicid();
        if (comicid != null) {
            stmt.bindString(5, comicid);
        }
 
        String chapterid = entity.getChapterid();
        if (chapterid != null) {
            stmt.bindString(6, chapterid);
        }
        stmt.bindLong(7, entity.getCollect() ? 1L: 0L);
        stmt.bindLong(8, entity.getHistory() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Manhua entity) {
        stmt.clearBindings();
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(1, name);
        }
 
        String cover = entity.getCover();
        if (cover != null) {
            stmt.bindString(2, cover);
        }
 
        String tag = entity.getTag();
        if (tag != null) {
            stmt.bindString(3, tag);
        }
 
        String detial = entity.getDetial();
        if (detial != null) {
            stmt.bindString(4, detial);
        }
 
        String comicid = entity.getComicid();
        if (comicid != null) {
            stmt.bindString(5, comicid);
        }
 
        String chapterid = entity.getChapterid();
        if (chapterid != null) {
            stmt.bindString(6, chapterid);
        }
        stmt.bindLong(7, entity.getCollect() ? 1L: 0L);
        stmt.bindLong(8, entity.getHistory() ? 1L: 0L);
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public Manhua readEntity(Cursor cursor, int offset) {
        Manhua entity = new Manhua( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // name
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // cover
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // tag
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // detial
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // comicid
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // chapterid
            cursor.getShort(offset + 6) != 0, // collect
            cursor.getShort(offset + 7) != 0 // history
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Manhua entity, int offset) {
        entity.setName(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setCover(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTag(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setDetial(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setComicid(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setChapterid(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setCollect(cursor.getShort(offset + 6) != 0);
        entity.setHistory(cursor.getShort(offset + 7) != 0);
     }
    
    @Override
    protected final String updateKeyAfterInsert(Manhua entity, long rowId) {
        return entity.getName();
    }
    
    @Override
    public String getKey(Manhua entity) {
        if(entity != null) {
            return entity.getName();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Manhua entity) {
        return entity.getName() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
